# Generated by Django 5.0.2 on 2024-04-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wnApp', '0008_country_state_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
