# Generated by Django 5.0.2 on 2024-04-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnApp', '0018_alter_profile_city_alter_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('', 'Select City'), ('AHM', 'Ahmedabad'), ('GN', 'Gandhinagar'), ('MEH', 'Mehsana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('', 'Select State'), ('GUJ', 'Gujarat'), ('M', 'Madhya Pradesh'), ('AS', 'Assam')], max_length=100),
        ),
    ]
