# Generated by Django 5.0.2 on 2024-04-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnApp', '0009_remove_state_country_delete_city_delete_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=100),
        ),
    ]
