# Generated by Django 5.0.2 on 2024-04-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnApp', '0014_alter_profile_country_alter_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('', 'Select City'), ('AHM', 'Ahmedabad'), ('GN', 'Gandhinagar'), ('MEH', 'Mehsana')], max_length=100),
        ),
    ]
